### ISSUE TITLE
output netcdf debug files when debug set to False

### ISSUE THREAD

**Issue by lizaclark** [NCAR/GARD#45]
I am running GARD from the SHARP branch with the following config file settings. Even though `debug` is set to `False`, [several netcdf files that are related to the debug option](https://github.com/NCAR/GARD/blob/SHARP/src/main/main.f90#L66-L89) are still created: `obs_preload_pcp.nc`, `training_preload_APCP_surface.nc`, `prediction_preload_APCP_surface.nc`, `obs_preload_t_mean.nc`, `training_preload_TMP_2maboveground.nc`, `prediction_preload_TMP_2maboveground.nc`.

This seems to only happen when using the `pure_regression` option, and not the `pass_through` option. I haven't been able to find a place where the `debug` option is reset outside of the `read_config()` module.
 
```
&parameters
    output_file     = "/d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/pure_regression/PNW/20170117/gard_output.pure_regression.20170117.p01.0dy.PNW."

    n_analogs        = 200

    start_date       = "2017-01-16 00:00:00"
    end_date         = "2017-01-16 00:00:00"

    start_train      = "2006-01-01 00:00:00"
    end_train        = "2009-12-31 00:00:00"

    start_transform  = "2006-01-01 00:00:00"
    end_transform    = "2009-12-31 00:00:00"

    pure_regression   = True
    pure_analog       = False
    analog_regression = False
    pass_through = False

    write_coefficients = False
    read_coefficients = True
    coefficients_files = /d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/pure_regression/PNW/20170117/gard_output.pure_regression.20170113.p01.0dy.PNW.t_mean_coef.nc

    sample_analog = False
    logistic_from_analog_exceedance = False
    logistic_threshold = -9999

    debug = False
    interactive = False
/

&training_parameters
    name = "GEFS training data"
    interpolation_method = 2
    time_indices = 5,6,7,8,9,10,11,12
    agg_method = 0
    time_weights = 3,3,3,3,3,3,3,3
    nvars     = 1
    data_type = "GEFS"
    lat_name  = "latitude"
    lon_name  = "longitude"
    time_name = "time"
    nfiles    = 1461

    input_transformations = 0

    var_names = TMP_2maboveground
    file_list = "/d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/gard_filelists/gard_filelist.gefs.TMP_2maboveground.mean.20060101-20091231.gefs.txt"

    selected_time = -1
    calendar  = "gregorian"
    timezone_offset = -8
/

&prediction_parameters
    name = "GEFS prediction data"
    interpolation_method = 2
    normalization_method = 2
    time_indices = 5,6,7,8,9,10,11,12
    time_weights = 3,3,3,3,3,3,3,3
    agg_method = 0
    nvars     = 1
    data_type = "GEFS"
    lat_name  = "latitude"
    lon_name  = "longitude"
    time_name = "time"
    nfiles    = 1

    input_transformations = 0

    var_names = TMP_2maboveground
    file_list = "/d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/gard_filelists/gard_filelist.gefs.TMP_2maboveground.p01.20170117.gefs.txt"
    calendar  = "gregorian"
    timezone_offset = -8
/


&obs_parameters
    name = "SHARP Newman Ensemble"
    nvars     = 1
    nfiles    = 1
    data_type = "obs"
    lat_name  = "latitude"
    lon_name  = "longitude"
    time_name = "time"

    input_transformations = 0
    var_names = t_mean
    file_list = "/d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/gard_filelists/gard_
filelist.obs.t_mean.mean.20091231.PNW.txt"

    calendar  = "gregorian"
/
```

**Comment by gutmann** [comment]
Thanks, I’ll have a quick look.

**Comment by gutmann** [comment]
can confirm I see this too... still looking

**Comment by lizaclark** [comment]
Thanks @gutmann. At @jhamman's suggestion, I pulled down the repo again, recompiled and ran a test case in case we had some local change. I still get the output files.

**Comment by gutmann** [comment]
weird: 
`        print*, "default=",debug
        ! read namelists
        open(io_newunit(name_unit), file=trim(options%options_filename))
        read(name_unit,nml=parameters)
        close(name_unit)
        print*, "post-namelist=",debug
`

outputs: 
` default= T
 post-namelist= T
`

**Comment by gutmann** [comment]
yes, I'm trying with the latest code too.

**Comment by lizaclark** [comment]
Does the `coefficients_filename` value need to be in quotation marks in the namelist? 
`coefficients_files = "/d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/pure_regression/PNW/20170113/gard_output.pure_regression.20170113.p10.6dy.PNW.t_mean_coef.nc"`
instead of 
`coefficients_files = /d2/hydrofcst/overtheloop/data/met_fcst/gefs/grid_nc/pure_regression/PNW/20170113/gard_output.pure_regression.20170113.p10.6dy.PNW.t_mean_coef.nc`

**Comment by gutmann** [comment]
but now I'm scratching my head, because that code should work... makes it look like there is an error in the namelist, or ifort.

**Comment by gutmann** [comment]
can't hurt to put it in quotes, but I don't think it should matter (since there are no funny characters in the name)

**Comment by gutmann** [comment]
putting it in quotes seems to fix it though... grrr

**Comment by lizaclark** [comment]
That's what I was about to say!

**Comment by lizaclark** [comment]
Quotes around string variables is an easy enough fix on my end. Do you think it's just a fortran quirk?

**Comment by gutmann** [comment]
:)

So maybe we add a note to the docs that filenames / other strings should always be in quotes.

**Comment by gutmann** [comment]
and yes, it may just be a fortran quirk

worse it may be a specific compiler quirk, with a different version it might work fine... sigh.

**Comment by andywood** [comment]
I wonder if without the quotes, you get either (1) a separation of the
filename from the rest of its path, so that the file is not found and then
created in the run directory; or (2) an overflow somewhere that resets the
true/false of the options later?

**Comment by gutmann** [comment]
Resolved by PR #46 not a complete solution, but I think this is basically a "this is how fortran namelists might work" error, not a gard error

**Comment by gutmann** [comment]
@andywood yes, one or both of those is likely.  I don't *think* it should overflow, as filenames have 1024 characters of space allocated, but who knows.  This is fortran after all 😛

**Comment by andywood** [comment]
let's not close this until we determine why it's happening

**Comment by lizaclark** [comment]
Could the "/" at the start of the file name be read as the end of the `parameters` section of the namelist file?

**Comment by gutmann** [comment]
If I change the filename to just coef.nc it works without quotes
if I put that file in a subdirectory (e.g. test/) then it breaks. 
yes, I think @lizaclark is right, the / is the problem, though it doesn't have to be at the beginning.  Anywhere in the name will break it without quotes.  

When I use test/coef.nc and print out the file names, it only prints test, not test/coef.nc, (though the second name in the list is blank, so it doesn't put coef.nc into the next array element.)

**Comment by gutmann** [comment]
And yes, the / may be read as an "end-of-namelist" string.  That makes the most sense as I think it is also setting "interactive" to true, even though it is set as false by default.

**Comment by gutmann** [comment]
Indeed, putting the coef file line at the end of that namelist correctly sets debug to false (though it still doesn't read anything other than testdir into the filename so it won't work)

**Comment by gutmann** [comment]
I think we can close this.

**Comment by andywood** [comment]
Great job debugging, all (not me)!
