### ISSUE TITLE
Do we need to check for recombination, if we have a species tree?

### ISSUE THREAD

**Issue by AswinSSoman** [NCAR/GARD#78]
Since the effect of recombination is in phylogenetic tree inference from a multiple sequence alignment, if we have a species tree available (independent of MSA), do we need to check for recombination in the sequences using GARD to avoid its effect on selection analysis?

**Comment by gutmann** [comment]
Hi Aswin Soman, 
I'd be happy to try to help, but I'm not sure I fully understand the question.  Can you provide a bit more information here on your use case and what you are recombining? (keeping in mind that I am not a biologist ;) )

regards,
Ethan

**Comment by AswinSSoman** [comment]
Hi Gutmann,
I want to do a selection analysis (relaxed/positive selection using hyphy) on a set of species. My inputs are MSA and a labeled phylogenetic tree. Since a species tree was available from the literature, I didn't need to build a tree using any phylogenetic methods. 
From what I have understood from the paper of GARD is, if the sequences have undergone recombination, different regions of the MSA may yield different phylogenies, which will increase false positives in the further step of selection inference. I want to know, if I already have a species tree, which is a much more accurate representation of phylogeny for the entire alignment, will the presence of recombination still affect the selection inference?

regards,
Aswin

**Comment by gutmann** [comment]
Which paper of GARD are you referring to?  I haven't actually published this work yet, so I wonder if there is another GARD model out there that you are looking for?

**Comment by AswinSSoman** [comment]
Sorry for the inconvenience, it was for a different tool.
